---
lang: pt
project:
  type: book
engines: [julia]
julia:
  env: [QT_QPA_PLATFORM=xcb]
execute:
  echo: false
  cache: true
filters:
  - diagram
diagram:
  cache: true
  engine:
    tikz:
      header-includes:
        - '\usetikzlibrary{patterns}'
        - '\usetikzlibrary{arrows}'
        - '\usetikzlibrary{automata}'
        - '\usetikzlibrary{calc}'
        - '\usetikzlibrary{positioning}'
        - '\usetikzlibrary{quotes}'
        - '\usepackage{pgfplots}'
        - '\usepackage{mathrsfs}'
        - '\pgfplotsset{compat=1.16}'
book:
  title: Anotações de Inferência Frequentista
  author: Aulas de Alexandre G. Patriota, digitado por Gustavo S. Garone
  date: last-modified
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/GustavoGarone/anotacoes-inferencia
        aria-label: GitHub
      - text: <i class='fa-solid fa-file-pdf'></i> PDF
        href: Anotações-de-Inferência-Frequentista.pdf
        # icon: download
  favicon: theta.png
  chapters:
    - index.qmd
    - part: Introdução à Inferência Frequentista
      chapters:
        - modelo-estatistico.qmd
        - populacao-e-amostra.qmd
        - quantidade-de-interesse.qmd
        - dist-amostral.qmd
        - funcao-verossimilhanca.qmd
        - estatisticas.qmd
        - estimadores.qmd
        - eqm-e-vies.qmd
        - monte-carlo.qmd
        - emv.qmd
        - qui-quadrado.qmd
        - tlc.qmd
        - estimador-intervalar.qmd
        - teste-hipotese.qmd
        - teste-hipotese-duas-pops.qmd
        - teste-nao-para-media.qmd
        - tabela-frequencias.qmd
        - analise-aderencia.qmd
        - testes-ind-homo.qmd
        - val-p.qmd
    - part: Inferência Frequentista
      chapters:
        - familia-exponencial.qmd
        - distribuicao-amostral.qmd
        - estatisticas-suficientes.qmd
        - estatisticas-ancilares.qmd
        - estatisticas-completas.qmd
        - envvum.qmd
        - escore.qmd
        - infofisher.qmd
        - estimadores-eficientes.qmd
        - estimadores-consistentes.qmd
        - escolha-estimador.qmd
        - emv2.qmd
        - metodo-momentos.qmd
        - metodo-nr.qmd
        - cond-regular.qmd
        - slutsky.qmd
        - prop-est.qmd
        - normal-multivariada.qmd
        - intervalos-confianca.qmd
        - teste-hipotese2.qmd
        - teste-neyman-pearson.qmd
        - tump.qmd
        - testes-gerais.qmd
        - val-p2.qmd
        - wishart.qmd
        - hotelling.qmd
        - regiao-confianca-normal.qmd
    # - references.qmd
bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl
format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    respect-user-color-scheme: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    extract-media: ./tikzdesigns/
    fig-cap-location: top
    fig-align: center
  pdf:
    documentclass: scrreport
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{cancel}
    #      \usepackage{amsmath}
    fig-cap-location: top
    fig-align: center
    default-image-extension: tex
    lof: true
    lot: true
    geometry:
      - top = 30mm
      - left = 30mm
      - right = 20mm
      - bottom = 20mm
    # mathfont: "ams"
    monofont: "Consolas"
  latex:
    documentclass: scrreport
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{cancel}
    #      \usepackage{asmath}
    fig-cap-location: top
    fig-align: center
    default-image-extension: tex
