lang: pt

project:
  type: book


execute:
  echo: false
  daemon: false
jupyter: julia-1.11
book:
  title: "Anotaçõess de Inferência Frequentista"
  author: "Aulas de Alexandre G. Patriota, digitado por Gustavo S. Garone"
  date: last-modified
  chapters:
    - part: "Introdução à Inferência Frequentista"
      chapters:
      - index.qmd
      - modelo-estatistico.qmd
      - populacao-e-amostra.qmd
      - quantidade-de-interesse.qmd
      - dist-amostral.qmd
      - funcao-verossimilhanca.qmd
      - estatisticas.qmd
      - estimadores.qmd
      - eqm-e-vies.qmd
      - monte-carlo.qmd
      - emv.qmd
      - qui-quadrado.qmd
      - tlc.qmd
      - estimador-intervalar.qmd
      - teste-hipotese.qmd
      - teste-hipotese-duas-pops.qmd
      - tabela-frequencias.qmd
      - analise-aderencia.qmd
      - testes-ind-homo.qmd
    - part: "Inferência Frequentista"
      chapters:
      - familia-exponencial.qmd
    # - references.qmd

bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl 

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  #   cite-method: biblatex



