lang: pt

project:
  type: book


execute:
  echo: false
  daemon: false
jupyter: julia-1.11
book:
  title: "Anotações de Inferência Frequentista"
  author: "Aulas de Alexandre G. Patriota, digitado por Gustavo S. Garone"
  date: last-modified
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/GustavoGarone/anotacoes-inferencia
        aria-label: GitHub
  favicon: theta.png
  chapters:
    - index.qmd
    - part: "Introdução à Inferência Frequentista"
      chapters:
      - modelo-estatistico.qmd
      - populacao-e-amostra.qmd
      - quantidade-de-interesse.qmd
      - dist-amostral.qmd
      - funcao-verossimilhanca.qmd
      - estatisticas.qmd
      - estimadores.qmd
      - eqm-e-vies.qmd
      - monte-carlo.qmd
      - emv.qmd
      - qui-quadrado.qmd
      - tlc.qmd
      - estimador-intervalar.qmd
      - teste-hipotese.qmd
      - teste-hipotese-duas-pops.qmd
      - tabela-frequencias.qmd
      - analise-aderencia.qmd
      - testes-ind-homo.qmd
    - part: "Inferência Frequentista"
      chapters:
      - familia-exponencial.qmd
      - distribuicao-amostral.qmd
      - estatisticas-suficientes.qmd
      - estatisticas-ancilares.qmd
      - estatisticas-completas.qmd
      - envvum.qmd
      - escore.qmd
      - infofisher.qmd
      - estimadores-eficientes.qmd
      - estimadores-consistentes.qmd
      - escolha-estimador.qmd
      - emv2.qmd
      - metodo-momentos.qmd
      - metodo-nr.qmd
      - prop-est.qmd
      - slutsky.qmd
      - cond-regular.qmd
    # - references.qmd

bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl 

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  #   cite-method: biblatex



