# Função Escore

Seja $\boldsymbol{X}_n$ [amostra aleatória](populacao-e-amostra.qmd#sec-aa) de $X\sim f_\theta, \theta \in \Theta$.
Considere $\boldsymbol{x}=(x_1,\dots,x_n)$ uma [amostra observada](populacao-e-amostra.qmd#sec-ao). A
[função de verossimilhança](funcao-verossimilhanca.qmd) $L_{\boldsymbol{x}_n} : \Theta \rightarrow \mathbb{R}$ é
definida por
$$
L_{\boldsymbol{x}_n}(\theta) = f_\theta^{\boldsymbol{X}_n}(\boldsymbol{x}_n)
$$
em que $f_\theta^{\boldsymbol{X}_n}$ é a [função (densidade) de probabilidade da amostra](dist-amostral.qmd). Assuma que
$f_\theta$ é diferenciável com respeito a "$\theta$", $\forall \theta \in \Theta$. A *função escore* é definida por
$$
U : \mathfrak{X} \times \Theta \rightarrow \mathbb{R}^P, \Theta \subseteq \mathbb{R}^P
$$
e $\mathfrak{X} = \{x : f_\theta(x) > 0\}$ é o suporte de $X$, tal que
$$
U(x,\theta) = \frac{\partial \ln f_\theta(x)}{\partial \theta} = \left(
\begin{array}{c}
\frac{\partial \ln f_\theta(x)}{\partial \theta_1} \\
\vdots \\
\frac{\partial \ln f_\theta(x)}{\partial \theta_P} \\
\end{array}
\right)
$$
e a função escore da amostra é definida por
$$
U_n(\boldsymbol{x}_n,\theta) = \frac{\partial \ln L_{\boldsymbol{x}_n}(\theta)}{\partial \theta} = \left(
\begin{array}{c}
\frac{\partial \ln L_{\boldsymbol{x}_n}(\theta)}{\partial \theta_1} \\
\vdots \\
\frac{\partial \ln L_{\boldsymbol{x}_n}(\theta)}{\partial \theta_P} \\
\end{array}
\right)
$$

Note que, para amostras aleatórias,
$$
U_n(\boldsymbol{x}_n,\theta) = \sum^n_{i=1} U(x_i, \theta)
$$
pois, por definição,
$$
\begin{aligned}
U_n(\boldsymbol{x}_n, \theta) = \frac{\partial \ln L_{\boldsymbol{x}_n}(\theta)}{\partial \theta}
&= \frac{\partial \ln }{\partial \theta} \prod f_\theta(x_i) \\
&= \frac{\partial }{\partial \theta} \sum \ln f_\theta(x_i) \\
&= \sum \frac{\partial \ln f_\theta(x_i)}{\partial \theta} \\
&= \sum U(x_i, \theta).
\end{aligned}
$$

## Condições de regularidade {#sec-condicoes}

$C_1: \mathfrak{X} = \{x : f_\theta (x) > 0 \}$ não depende de "$\theta$".

$C_2: f_\theta$ é duas vezes diferenciável com respeito a "$\theta$" e suas derivadas são contínuas.

$C_3:$ é possível trocar as derivadas pela integrais da seguinte forma:
$$
\left\{\begin{aligned}
&a)\ \frac{\partial}{\partial\theta} \int f_\theta(x) dx &= \int \frac{\partial}{\partial \theta} f_\theta(x) dx \\
&b)\ \frac{\partial^2}{\partial \theta \partial \theta^T} \int f_\theta(x) dx &= \int \frac{\partial^2}{\partial \theta \partial \theta^T} f_\theta(x) dx
\end{aligned}\right.
$$

$C_4:$
$$
\left\{\begin{aligned}
&\mathrm{a})\ E_\theta\left(\lVert\frac{\partial}{\partial\theta} \ln f_\theta(x)\rVert\right) < \infty,\ \forall \theta \in \Theta \\
&\mathrm{b})\ E_\theta\left(\lVert\frac{\partial^2}{\partial\theta\partial\theta^T} \ln f_\theta(x)\rVert^2\right) < \infty,\ \forall \theta \in \Theta.
\end{aligned}\right.
$$

Para as duas últimas condições, substituímos no caso discreto as integrais por somatórios.

Nas provas e listas, se não afirmado o contrário (explicitamente ou com suporte dependendo de $\theta$), os exemplos
satisfazem as condições de regularidade.

### Teorema (das condições do escore) {#sec-teo-condicoes}
Seja $\boldsymbol{X}_n$ a.a. de $X\sim f_\theta, \theta \in \Theta \subseteq \mathbb{R}^P$. Se as condições $C_1 : C_4$
estiverem satisfeitas, então
$$
E_\theta(U_n(\boldsymbol{X}_n,\theta)) = 0,\ \forall \theta \in \Theta.
$$

#### Prova

Note que $U_n(\boldsymbol{X}_n,\theta) = \sum U(X_i,\theta)$. Por $C_4(a)$, podemos calcular a esperança:
$$
\begin{aligned}
E_\theta(U_n(\boldsymbol{X}_n,\theta)) &= \sum E_\theta(U(X_i,\theta)) \\
&\stackrel{\mathrm{id.}}{=} nE_\theta(U(X,\theta)) \\
\Rightarrow E_\theta(U(X,\theta)) &= \int_{\mathfrak{X}} U(x,\theta)f_\theta(x)dx \\
&= \int_{\mathfrak{X}} \frac{\partial}{\partial\theta}\ln f_\theta(x) \cdot f_\theta(x) dx \\
&= \int_{\mathfrak{X}} \frac{\partial}{\partial\theta} f_\theta(x) dx, \forall \theta \in \Theta
\end{aligned}
$$

Note que
$$
\int_{\mathfrak{X}} f_\theta(x)dx = 1, \forall \theta \in \Theta
$$

Logo, por $C_3$
$$
\frac{\partial}{\partial \theta} \int_{\mathfrak{X}}  f_\theta(x) dx = 0
= \int_{\mathfrak{X}} \frac{\partial}{\partial \theta} f_\theta(x) dx,\ \forall \theta \in \Theta
$$

## Informação de Fisher {#sec-infofisher}

Seja $U(X,\theta)$ função escore. A informação de Fisher é a variância da função escore:
$$
I_1(\theta) = \mathrm{Var}_\theta(U(X,\theta))
$$

A informação de Fisher total é a variância da função escore da amostra:
$$
I_n(\theta) = \mathrm{Var}_\theta(U_n(\boldsymbol{X}_n,\theta))
$$

Note que, sob as [condições](escore.qmd#sec-condioces) $C_1:C_4$, [temos que](escore.qmd#sec-teo-condicoes)
$$
\begin{aligned}
&E_\theta(U(X,\theta)) = 0,\ \forall \theta \in \Theta \\
&E_\theta(U(\boldsymbol{X}_n, \theta)) = 0,\ \forall \theta \in \Theta \\
\Rightarrow &\left\{\begin{array}{ll}
I_1(\theta) = E_\theta(U(X,\theta)\cdot U(X,\theta)^T) \\
I_n(\theta) = E_\theta(U_n(\boldsymbol{X}_n,\theta)\cdot U_n(\boldsymbol{X}_n,\theta)^T)\\
\end{array}\right.\ \forall \theta \in \Theta \\
&\text{Se } \Theta \in \mathbb{R}, \\
\Rightarrow &\left\{\begin{array}{ll}
I_1(\theta) = E_\theta(U(X,\theta)^2) \\
I_n(\theta) = E_\theta(U_n(\boldsymbol{X}_n,\theta)^2)\\
\end{array}\right.\ \forall \theta \in \Theta \\
\end{aligned}
$$

### Teorema (da informação de Fisher sob as condições) {#sec-teo-infofisher}

Sob as [condições](escore.qmd#sec-condioces) $C_1:C_4$, temos que

$$
\left\{\begin{array}{ll}
I_1(\theta) = - E_\theta\left(\frac{\partial}{\partial \theta^T} U(X,\theta\right) \\
I_n(\theta) = - E_\theta\left(\frac{\partial}{\partial \theta} U_n(\boldsymbol{X}_n,\theta^T\right)
\end{array}\right.\ \forall \theta \in \Theta
$$

#### Prova

Sem perda de generalidade, considere apenas o caso contínuo e $\Theta \subseteq \mathbb{R}$.

Sabemos que $U(X,\theta) = \frac{\partial}{\partial\theta}f_\theta(x)$. Além disso,
$$
\int_{\mathfrak{X}} f_\theta(x) dx = 1,\ \forall \theta \in \Theta
$$
em que $\mathfrak{X} = \{x : f_\theta(x) > 0\}$ não depende de "$\theta$".

Por $C_3(b)$,
$$
\frac{\partial^2}{\partial \theta \partial \theta^T} \int_{\mathfrak{X}} f_\theta(x) dx
= \int_{\mathfrak{X}} \frac{\partial^2}{\partial \theta \partial \theta^T} f_\theta(x) dx = 0, \forall \theta \in \Theta
$$ {#eq-c30}

Note que
$$
\begin{aligned}
I_1(\theta) &= E_\theta(U(X,\theta)^2) \\
&= \int_{\mathfrak{X}} U(x,\theta)^2 f_\theta(x)dx \\
&= \int_{\mathfrak{X}} \left[\frac{\partial \ln}{\partial \theta} f_\theta(x)\right]^2 f_\theta(x)dx,\ \forall \theta \in \Theta
\end{aligned}
$$ 

Observe que, por ([-@eq-c30]), 
$$
\begin{aligned}
&\int_{\mathfrak{X}}\frac{\partial}{\partial\theta} \left[\frac{\partial f_\theta(x)}{\partial \theta} \frac{f_\theta(x)}{f_\theta(x)}\right]dx = 0\\
\Rightarrow &\int_{\mathfrak{X}}\frac{\partial}{\partial\theta} \left[\frac{\partial \ln f_\theta(x)}{\partial \theta} f_\theta(x)\right]dx = 0 \\
\Rightarrow &\int_{\mathfrak{X}}\frac{\partial}{\partial\theta}
\left[\frac{\partial^2 \ln f_\theta(x)}{\partial \theta^2} f_\theta(x) +
\frac{\partial\ln f_\theta(x)}{\partial\theta}\frac{\partial f_\theta(x)}{\partial\theta}\right]dx = 0\\
\Rightarrow &\int_{\mathfrak{X}}
\frac{\partial^2 \ln f_\theta(x)}{\partial \theta^2} f_\theta(x) +
\int_{\mathfrak{X}} \frac{\partial\ln f_\theta(x)}{\partial\theta}\frac{\partial f_\theta(x)}{\partial\theta}dx = 0\\
\Rightarrow &E_\theta\left(
\frac{\partial^2 \ln }{\partial \theta^2} f_\theta(X)\right) +
\int_{\mathfrak{X}} \frac{\partial\ln f_\theta(x)}{\partial\theta}\frac{\partial\ln f_\theta(x)}{\partial\theta}f_\theta(x)dx = 0\\
\Rightarrow &-E_\theta\left(
\frac{\partial^2 \ln }{\partial \theta^2} f_\theta(X)\right) =
E_\theta\left(\left[\frac{\partial\ln}{\partial\theta^2}f_\theta(X)\right]^2\right) \\
\Rightarrow &E_\theta(U(X,\theta)^2)= -E_\theta\left(\frac{\partial U(X,\theta)}{\partial \theta}\right) \\
\Rightarrow &I_1(\theta) = -E_\theta\left(\frac{\partial U(X,\theta)}{\partial \theta}\right),\ \forall \theta \in \Theta.
\end{aligned}
$$

Ademais, temos que
$$
I_n(\theta) = \mathrm{Var}_\theta(U_n(\boldsymbol{X}_n, \theta)) \stackrel{C_1:C_4}{=} E_\theta(U_n(\boldsymbol{X}_n,\theta)^2)
$$
Sabemos que $U_n(\boldsymbol{X}_n,\theta) = \sum\limits^n_{i=1} U(X_i,\theta)$. Portanto,
$$
\begin{aligned}
I_n(\theta) &= E_\theta\left[\left( \sum U(X_i,\theta)\right)^2\right]\\
&= E_\theta(\sum_i\sum_j U(X_i,\theta)U(X_j,\theta)) \\
&= E_\theta\left(\sum_{i=1}^n U(X_i,\theta)^2 + \sum_{i\neq j} U(X_i,\theta) U(X_j,\theta)\right) \\
&= \sum E_\theta (U(X_i,\theta)^2) + \sum_{i\neq j }E_\theta(U(X_i,\theta)U(X_j,\theta)), \forall \theta \in \Theta.
\end{aligned}
$$

Como $X_1,\dots,X_n$ são i.i.d, temos que $U(X_1,\theta),\dots,U(X_n,\theta)$ também são i.i.d. Logo,
$$
I_n(\theta) = \sum E_\theta(U(X_i,\theta)^2) + \sum_{i\neq j} E_\theta(\cancelto{0}{U(X_i,\theta)}) E_\theta(\cancelto{0}{U(X_j,\theta)})
$$

Por ser i.i.d., temos portanto que
$$
I_n(\theta) = nI_1(\theta)
$$

Note também que
$$
\begin{aligned}
E_\theta\left(\frac{\partial}{\partial\theta}U(\boldsymbol{X}_n, \theta)\right) &= E_\theta\left(\frac{\partial}{\partial \theta} \sum U(X_i,\theta)\right) \\
&= E_\theta\left(\sum \frac{\partial}{\partial \theta} U(X_i,\theta)\right) \\
&= n E_\theta\left(\frac{\partial}{\partial \theta} U(X_i,\theta)\right),\ \forall \theta \in \Theta.
\end{aligned}
$$

Como $I_1(\theta) = - E_\theta\left(\frac{\partial}{\partial} U(X,\theta)\right)$. Temos que
$$
\begin{aligned}
&-E_\theta\left(\frac{\partial}{\partial \theta} U(\boldsymbol{X}_n,\theta)\right) = n I_1(\theta) \\
\Rightarrow &I_n(\theta) = nI_1(\theta) = -E_\theta\left(\frac{\partial}{\partial \theta} U(\boldsymbol{X}_n,\theta)\right), \forall \theta \in \Theta._\blacksquare
\end{aligned}
$$

### Exemplo

Seja $\boldsymbol{X}_n$ a.a de $X\sim f_\theta, \theta\in \mathbb{R}_+$, tal que
$$
f_\theta(x) = \left\{\begin{array}{ll}
\theta x^{\theta-1},& x \in (0,1) \\
0,& \mathrm{c.c.}
\end{array}\right.
$$

Encntre a função [escore](escore.qmd) da amostra e a [informação de Fisher](escore.qmd#sec-infofisher) total.

#### Resposta

Note que
$$
L_{\boldsymbol{X}_n} = \prod^n \left\{ \theta x_i^{\theta-1}\right\} = \theta^n (\prod x_i)^{\theta-1},\ \forall \theta \in \Theta.
$$

A função escore da amostra é
$$
\begin{aligned}
U_n(\boldsymbol{X}_n,\theta) &= \frac{\partial}{\partial \theta} \ln L_{\boldsymbol{X}_n} (\theta) \\
&= \frac{\partial}{\partial \theta} \left[n \ln \theta + (\theta-1) \sum \ln x_i\right] \\
&= \frac{n}{\theta} + \sum \ln x_i, \forall \theta \in \Theta.
\end{aligned}
$$

A informação de Fisher total é, pelo [teorema](escore.qmd#sec-teo-infofisher),
$$
I_n(\theta) = - E_\theta\left(\frac{\partial}{\partial \theta} U_n(\boldsymbol{X}_n,\theta)\right), \forall \theta \in \Theta.
$$

Note que
$$
\frac{\partial}{\partial \theta} U_n(\boldsymbol{X}_n,\theta) = - \frac{n}{\theta^2}, \forall \theta \in \Theta.
$$

Portanto,
$$
I_n(\theta) = -\frac{n}{\theta^2}, \forall \theta \in \Theta.
$$

### Exemplo (Binomial)

Seja $\boldsymbol{X}_n$ a.a. de $X \sim \mathrm{Bin}(3,\theta), \theta \in (0,1)$. Encontre a função escore e a informação
de Fisher total.

#### Resposta

Note que
$$
\begin{aligned}
L_{\boldsymbol{X}_n} &= \prod f_\theta(x) = \prod \left\{\binom{3}{x_i} \theta^{x_i} (1-\theta)^{3-x}\right\} \\
\Rightarrow \ln L_\boldsymbol{X_n} &= \sum \ln \binom{3}{x_i} + \sum x_i \ln \theta + \sum (3-x_i)\ln(1-\theta) \\
\Rightarrow U_n(\boldsymbol{x}_n,\theta) = \sum \frac{x_i}{\theta} + \sum \frac{(3-x_i)}{1-\theta} (-1) \\
& = \frac{x_i}{\theta} - \sum \frac{(3-x_i)}{1-\theta},\ \forall \theta \in \Theta.
\end{aligned}
$$

A informação de Fisher total é, pelo [teorema](escore.qmd#sec-teo-infofisher),
$$
\begin{aligned}
I_n(\theta) &= - E_\theta\left(\frac{\partial}{\partial\theta} U_n(\boldsymbol{X}_n,\theta)\right) \\
&= - E_\theta\left( - \sum \frac{X_i}{\theta^2} + \sum \frac{(3-X)}{(1-\theta)^2}(-1)\right) \\
&= E_\theta\left(\sum \frac{X_i}{\theta^2} + \sum \frac{(3-X)}{(1-\theta)^2}\right) \\
&= \sum \frac{E_\theta(X_i)}{\theta^2} + \sum \frac{3 - E_\theta(X)}{(1-\theta)^2} \\
&= \frac{n 3\theta}{\theta^2} + \frac{n(3-3\theta)}{(1-\theta)^2} \\
&= \frac{ 3n}{\theta} + \frac{3n(1-\theta)}{(1-\theta)^2} \\
&= \frac{3n}{\theta} + \frac{3n}{(1-\theta)} \\
&= \frac{3n}{\theta(1-\theta)},\ \forall \theta \in \Theta.
\end{aligned}
$$

Podemos também fazer pela definição.


Observe que
$$
\begin{aligned}
E_\theta(U_n(\boldsymbol{X}_n,\theta) &= E_\theta\left(\sum \frac{X_i}{\theta} - \sum \frac{3-X_i}{1-\theta}\right) \\
&= \sum \frac{E_\theta(X_i)}{\theta} - \frac{(3-E_\theta(X_i)}{1-\theta} \\
&= \frac{n 3 \theta}{\theta} - \frac{n (3- 3\theta)}{1-\theta} \\
&= n3 - n3 \frac{1-\theta}{1-\theta} = 0,\ \forall \theta \in \Theta.
\end{aligned}
$$

$$
\begin{aligned}
I_n(\theta) &= \mathrm{Var}_\theta(U_n(\boldsymbol{X}_n,\theta)) \\
&= E_\theta(U_n(\boldsymbol{X},\theta)^2) \\
&= E_\theta\left(\left[\sum \left(\frac{X_i}{\theta} - \frac{(3-X_i)}{1-\theta}\right)\right]^2\right) \\
&= E_\theta\left(\sum_i \sum_j \left(\frac{X_i}{\theta} - \frac{(3-X_i)}{1-\theta}\right)\left(\frac{X_j}{\theta} - \frac{(3-X_j)}{1-\theta}\right)\right) \\
&= \sum_i E_\theta\left(\left(\frac{X_i}{\theta} - \frac{(3-X_i)}{1-\theta}\right)^2\right)
\underset{i \neq j}{\sum\sum}E_\theta\left(\cancelto{0}{\frac{X_i}{\theta} - \frac{(3-X_i)}{1-\theta}}\right)
E_\theta\left(\cancelto{0}{\frac{X_j}{\theta} - \frac{(3-X_j)}{1-\theta}}\right)\\
&= n E_\theta\left[\left( \frac{X}{\theta} - \frac{3-X}{1-\theta}\right)^2\right] \\
&= n E_\theta\left[\left( \frac{X(1-\theta)-(3-x)\theta}{\theta(1-\theta)}\right)^2\right] \\
&= \frac{n E_\theta\left[(X - \theta X - 3\theta + \theta X)^2\right]}{\theta(1-\theta)} \\
&= \frac{n E_\theta\left[(X - 3\theta)^2\right]}{\theta^2(1-\theta)^2} \\
&= \frac{n \mathrm{Var}_\theta}{\theta^2(1-\theta)^2} = \frac{n3\theta(1-\theta)}{\theta^2(1-\theta)^2}\\
&= \frac{3n}{\theta(1-\theta)},\ \forall \theta \in \Theta.
\end{aligned}
$$
