# Consistência

Dizemos que $T(\boldsymbol{X}_n)$ é um [estimador](estimadores.qmd) (fracamente) consistente para $g(\theta)$ se, e
somente se, para cada $\epsilon > 0$ fixo,

$$
\lim_{n\rightarrow \infty} P_\theta\left(\lvert T(\boldsymbol{X}_n) - g(\theta) \rvert > \epsilon\right) = 0, \forall \theta \in \Theta.
$$
ou
$$
T(\boldsymbol{X}_n) \stackrel{P_\theta}{\rightarrow} g(\theta),\ \forall \theta \in \Theta.
$$

::: {.callout-caution}
Alguns livros escrevem
$$
T(\boldsymbol{X}_n) \stackrel{p}{\rightarrow} g(\theta_0)
$$
em que $\theta_0$ é o verdadeiro valor de $\theta$ se, e somente se, para cada $\epsilon > 0$ fixado:
$$
\lim_{n\rightarrow \infty} P\left(\lvert T(\boldsymbol{X}_n) - g(\theta_0) \rvert > \epsilon\right) = 0.
$$
Apesar de ser uma forma comum de exposição para pessoas não treinadas em estatística, essa notação não está bem
formalizada na estrutura do modelo estatístico clássico.
:::

Dizemos $T(\boldsymbol{X}_n)$ é *fortemente* consistente se, e somente se,
$$
P_\theta\left(\lim_{n\rightarrow \infty} T(\boldsymbol{X}_n) = g(\theta)\right) = 1,\ \forall \theta \in \Theta.
$$
ou
$$
T(\boldsymbol{X}_n) \stackrel{\mathrm{q.c.}[P_\theta]}{\rightarrow} g(\theta),\ \forall \theta \in \Theta.
$$

::: {.callout-caution}
Alguns livros escrevem
$$
T(\boldsymbol{X}_n) \stackrel{\mathrm{q.c.}}{\rightarrow} g(\theta_0)
$$
em que $\theta_0$ é o verdadeiro valor de $\theta$ se, e somente se, 
$$
 P\left(\lim_{n\rightarrow \infty}T(\boldsymbol{X}_n) = g(\theta_0)\right) = 1.
$$
Apesar de ser uma forma comum de exposição para pessoas não treinadas em estatística, essa notação não está bem
formalizada na estrutura do modelo estatístico clássico.
:::


::: {.callout-note}
Quando se diz que $T(\boldsymbol{X}_n)$ é consistente para $g(\theta)$, sem especificar a convergência,
quer-se dizer que a convergência é fraca.
:::

::: {.callout-note}
$$
P_\theta(\underbracket{\lim_{n\rightarrow \infty} T(\boldsymbol{X}_n) = g(\theta)}_{\{\omega \in \Omega : \lim\limits_{n\rightarrow \infty}T(\boldsymbol{X}_n(\omega))=g(\theta)\}})
$$
:::

## Teorema (da relação com o EQM)

Seja $T(\boldsymbol{X}_n)$ um estimador para $g(\theta) \in \mathbb{R}$ tal que o [Erro Quadrático Médio](eqm-e-vies.qmd)
$$
\mathrm{EQM}_\theta(T(\boldsymbol{X}_n), g(\theta)) = E_\theta[(T(\boldsymbol{X}_n) - g(\theta))^2]
$$
converge para $0$ para cada $\theta \in \Theta$. Então, $T(\boldsymbol{X}_n)$ é fracamente consistente para $g(\theta)$

### Prova

Seja $\epsilon > 0$ fixado. Então,
$$
\begin{aligned}
P_\theta(\lvert T(\boldsymbol{X}_n) - g(\theta) \rvert > \epsilon) &= P_\theta((T(\boldsymbol{X}_n) - g(\theta))^2 > \epsilon^2) \\
&\stackrel{\mathrm{Chebyshev}}{\leq} \frac{E_\theta((T(\boldsymbol{X}_n - g(\theta))^2)}{\epsilon^2}
=  \frac{\mathrm{EQM}_\theta(T(\boldsymbol{X}_n),g(\theta))}{\epsilon^2} \\
\Rightarrow \lim_{n\rightarrow \infty} P_\theta(\lvert T(\boldsymbol{X}_n) - g(\theta) \rvert > \epsilon) &\leq  0,\ \forall \theta \in \Theta.
\end{aligned}
$$
Logo, $T(\boldsymbol{X}_n)\stackrel{P_\theta}{\rightarrow}g(\theta),\ \forall\theta \in\Theta.$

::: {.callout-note}
Se $\mathrm{EQM}_\theta(T(\boldsymbol{X}_n),g(\theta)) \stackrel{n\uparrow \infty}{\rightarrow} 0, \forall \theta \in \Theta$, então
$$
T(\boldsymbol{X}_n) \stackrel{P_\theta}{\rightarrow}g(\theta),\ \forall \theta \in \Theta.
$$

Usando desse recurso nos exercícios, basta mostrar que o EQM vai para zero quando $n$ cresce.
:::

::: {.callout-tip}
Disso, temos que, se $T(\pmb{X}_n)$ for [assintóticamente eficiente](estimadores-eficientes.qmd#sec-efassin), então será *fracamente* consistente.
:::

## Exemplos

### Exemplo Bernoulli

Seja $\pmb{X}_n$ [amostra aleatória](populacao-e-amostra.qmd#sec-aa) de $X\sim \mathrm{Ber}(\theta), \theta \in \Theta = (0,1)$.
Mostre que $T(\pmb{X}_n)$ é consistente para $g(\theta) = \theta$.

#### Resposta

Como $E_\theta(\bar{X}) = \theta$ e $\mathrm{Var}_\theta(\bar{X}) \frac{\theta(1-\theta)}{n}, \forall \theta \in \Theta.$,
temos que 
$$
\begin{aligned}
\mathrm{Viés}_\theta(\bar{X},\theta) &= 0, \forall \theta \in \Theta, \\
\lim_{n\rightarrow \infty} \mathrm{Var}_\theta(\bar{X}) = 0, \forall \theta \in \Theta, \\
\Rightarrow \mathrm{EQM}_\theta(\bar{X},\theta) &\rightarrow 0, \forall \theta \in \Theta
\Rightarrow \bar{X} \stackrel{P_\theta}{\rightarrow} \theta, \forall \theta \in \Theta.
\end{aligned}
$$

::: {.callout-tip}
Poderíamos também, como $\pmb{X}_n$ é uma amostra aleatória, utilizar a lei forte dos grandes números.
:::

### Exemplo Normal (média)

Seja $\pmb{X}_n$ a.a. de $X\sim \mathrm{N}(\mu,\sigma^2), \theta = (\mu,\sigma^2) \in \Theta = \mathbb{R}\times\mathbb{R}_+$.
Mostre que $\bar{X}$ é consistente para $g(\theta) = \mu.$

#### Resposta

Como $E_\theta(\bar{X}) = \mu, \mathrm{Var}_\theta(\bar{X}) = \frac{\sigma^2}{n}, \forall \theta \in \Theta$, temos que
$$
\begin{aligned}
\mathrm{Viés}_\theta(\bar{X},\mu) &= 0, \forall \theta \in \Theta, \\
\lim_{n\rightarrow \infty} \mathrm{Var}_\theta(\bar{X}) &= 0, \forall \theta \in \Theta, \\
\Rightarrow \lim_{n\rightarrow \infty} \mathrm{EQM}_\theta(\bar{X},\theta) &= 0, \forall \theta \in \Theta \\
\Rightarrow T(\pmb{X}_n) &= \bar{X} \text{ é fracamente consistente para } g(\theta) = \mu.
\end{aligned}
$$

### Exemplo Normal (variância)

Seja $\pmb{X}_n$ a.a. de $X\sim \mathrm{N}(\mu,\sigma^2), \theta = (\mu,\sigma^2) \in \Theta = \mathbb{R}\times\mathbb{R}_+$.
Mostre que
$$
T_k(\pmb{X}_n) = \frac{1}{n-k} \sum_{i=1}^n (X_i - \bar{X})^2
$$
é consistente para $g(\theta) = \sigma^2.$


#### Resposta

Sabemos que
$$
\sum_{i=1}^n \frac{(X_i - \bar{X})^2}{\sigma^2} \sim \chi^2_{(n-1)}, \forall \theta \in \Theta.
$$

Logo,
$$
\begin{aligned}
E_\theta(T_k(\pmb{X}_n)) &= E_\theta\left(\frac{1}{n-k} \sum (X_i - \bar{X})^2\right) \\
&= \frac{\sigma^2}{n-k}E_\theta\left(\sum \frac{(X_i - \bar{X})^2}{\sigma^2}\right) \\
&= \frac{\sigma^2}{n-k}(n-1), \forall \theta \in \Theta.
\end{aligned}
$$

Ademais,
$$
\begin{aligned}
\mathrm{Var}_\theta(T_k(\pmb{X}_n)) &= \mathrm{Var}_\theta\left(\frac{1}{n-k} \sum (X_i - \bar{X})^2\right) \\
&= \frac{\sigma^4}{(n-k)^2}\mathrm{Var}_\theta\left(\sum \frac{(X_i - \bar{X})^2}{\sigma^2}\right) \\
&= \frac{\sigma^4}{(n-k)^2}2(n-1), \forall \theta \in \Theta.
\end{aligned}
$$

Portanto,
$$
\mathrm{EQM}_\theta = \frac{2\sigma^2}{(n-k)^2}(n-1) + \left(\frac{\sigma^2}{n-k}(n-1) - \sigma^2\right)^2
$$

Como
$$
\lim_{n\rightarrow \infty} \frac{n-1}{n-k} = 1, \forall k \neq n, k \ \text{fixado}
$$
e
$$
\lim_{n\rightarrow \infty} \frac{n-1}{(n-k)^2} = 0, \forall k \neq n, k\ \text{fixado}
$$
temos que
$$
\lim_{n\rightarrow \infty} \mathrm{EQM}_\theta(T_k(\pmb{X}_n),\sigma^2) = 0, \forall \theta \in \Theta.
$$

Logo, $T(\pmb{X}_n)$ é consistente para $\sigma^2, \forall k \neq n, \ k \text{fixado}$
