# Família Exponencial (FE)
Podemos representar a função $f_\theta$ genericamente, incluindo funções de probabilidade e funções densidade
de probabilidade, por meio da família exponencial.

## Família Exponencial unidimensional
Dizemos que $f_\theta$ pertence à família exponencial unidimensional se, e somente se,

$$
f_\theta(x) = \left \{\begin{array}{lr}
\mathrm{e}^{c(\theta) T(x) + d(\theta) + S(x)}, & x \in \mathfrak{X} \\
0, & x \not \in \mathfrak{X}
\end{array} \right.
$$

em que $c(\cdot)$ e $d(\cdot)$ são funções de "$\theta$" cujas formas são conhecidas e $T(\cdot)$ e $S(\cdot)$ são funções
de $x$ com formas conhecidas, em que $\mathfrak{X} = \{x: f_\theta(x) > 0\}$ não depende de "$\theta$". $\mathfrak{X}$
é dito ser o suporte de $f_\theta$.

### Exemplos

#### Exemplo 1 - Exponencial {#sec-fe-exp}

Considere $X \sim f_\theta, \theta \in (0,\infty)$ em que
$$
f_\theta(x) = \left\{\begin{array}{lr}
\theta \mathrm{e}^{-\theta x}, & x > 0 \\
0, & \mathrm{c.c}
\end{array}\right.
$$

Ou seja, $X\sim \mathrm{Exp}(\theta), \theta > 0$. Mostre que $f_\theta$ pertence à família exponencial.

##### Resposta

Observe que $\mathfrak{X}=\{x:f_\theta(x)>0\} = (0, \infty)$ não depende de "$\theta$". Além disso, como $\theta > 0$,
temos que $\theta = \mathrm{e}^{\ln(\theta)}$. Portanto, para $x>0$, temos que
$$
f_\theta(x) = \mathrm{e}^{-\theta x + \ln \theta}
$$
Assim,
$$
\begin{array}{cc}
c(\theta) = -\theta, & d(\theta) = \ln \theta \\
T(x) = x, & S(x) = 0.
\end{array}
$$
Portanto, $f_\theta$ pertence à família exponencial.

#### Exemplo 2 - Bernoulli
Considere $X\sim \mathrm{Ber}(\theta), \theta \in \Theta = (0,1)$. Mostre que a sua função de probabilidade pertence
à família exponencial.

##### Resposta

Observe que 
$$
f_\theta(x) = \left\{\begin{array}{lr}
\theta^x \cdot (1-\theta)^{1-x}, & x \in \{0,1\} \\
0, & x \not \in \{0,1\}
\end{array}\right.
$$
o suporte é $\mathfrak{X} = \{ x : f_\theta(x)>0\} = \{0,1\}$ não depende de "$\theta$".

Além disso, como $\theta^x (1-\theta)^{1-x} > 0$, temos que
$$
\begin{aligned}
\theta^x (1-\theta)^{1-x} &= \mathrm{e}^{\ln(\theta^x(1-\theta)^{1-x})}\\ 
&= \mathrm{e}^{x\ln\theta + (1-x) \ln (1-\theta)}\\
&=\mathrm{e}^{x\ln\theta + \ln (1-\theta) - x \ln(1-\theta)} \\
&= \mathrm{e}^{x\left(\ln \theta - \ln(1-\theta)\right) + \ln(1-\theta)}\\
&=\mathrm{e}^{\ln\left(\frac{\theta}{1-\theta}\right)x+\ln(1-\theta)}
\end{aligned}
$$

logo, $f_\theta(x) = \mathrm{e}^{c(\theta)T(x)+d(\theta)+S(x)}, x \in \{0,1\}$, em que
$$
\begin{array}{cc}
c(\theta) = \ln(\frac{\theta}{1-\theta}), & T(x) = x \\
d(\theta) = \ln(1-\theta), & S(x) = 0.
\end{array}
$$
Portanto, $f_\theta$ pertence à família exponencial.

#### Exemplo 3 - Normal (Média)
Considere que $X\sim N(\theta,1), \theta \in \mathbb{R}$. Mostre que a sua função densidade de probabilidade pertence
à FE unidimensional.

#### Resposta
Note que 
$$
f_\theta(x) = \frac{1}{\sqrt{2\pi}} \mathrm{e} ^{-\frac{1}{2} (x-\theta)^2}, x \in \mathbb{R}
$$
o suporte é $\mathfrak{X} = \{x: f_\theta(x) > 0\} = (-\infty, \infty)$ e não depende de "$\theta$". Além disso, temos
que 
$$
\begin{aligned}
f_\theta(x) & = \mathrm{e}^{-\frac{1}{2}(x-\theta)^2-\ln\sqrt{2\pi}} \\
&= \mathrm{e}^{-\frac{1}{2}(x^2 - 2x\theta + \theta^2) - \ln\sqrt{2\pi}} \\
&= \mathrm{e}^{\theta x - \frac{1}{2}\theta^2 - \frac{1}{2}x^2 - \ln\sqrt{2\pi}}.
\end{aligned}
$$

Portanto, $f_\theta$ pertence à FE:
$$
\begin{array}{cc}
c(\theta) = \theta, & T(x) = x \\
d(\theta) = -\frac{1}{2}\theta^2, & S(x) = -\frac{1}{2}x^2-\ln\sqrt{2\pi}.
\end{array}
$$

#### Exempo 4 - Normal (Variância)
Considere que $X\sim N(0,\theta), \theta \in (0,\infty)$. Mostre que a sua função densidade de probabilidade pertence
à FE unidimensional.

##### Resposta
Observe que
$$
f_\theta(x) = \frac{1}{\sqrt{2\pi\theta}} \mathrm{e}^{-\frac{1}{2\theta}x^2}, x \in \mathbb{R}
$$

O suporte $\mathfrak{X} = \mathbb{R}$ não depende de "$\theta$".
Além disso,
$$
\begin{aligned}
f_\theta(x) &= \mathrm{e}^{-\frac{1}{2\theta}x^2 - \frac{1}{2} \ln(2\pi\theta)} \\
&= \mathrm{e}^{c(\theta)T(x)+d(\theta)+S(x)}
\end{aligned}
$$
em que
$$
\begin{array}{cc}
c(\theta) = -\frac{1}{2\theta}, & T(x) = x^2 \\
d(\theta) = -\frac{1}{2}\ln(2\pi\theta), & S(x) = 0.
\end{array}
$$

Portanto, $f_\theta$ pertence à FE.

#### Exemplo 5 - Normal (Média = Variância)
Seja $X\sim N(\theta, \theta)$, em que $\theta \in (0, \infty)$. Mostre que a sua
função densidade de probabilidade pertence à FE de dimensão 1.

##### Resposta
A função densidade de probabilidade de $X$ é 
$$
\begin{aligned}
f_\theta(x) &= \frac{1}{\sqrt{2\pi\theta}} \mathrm{e}^{-\frac{1}{2\theta}(x-\theta)^2} \\
&= \mathrm{e}^{-\frac{1}{2\theta}(x^2-2\theta x+ \theta^2) -\frac{1}{2}\ln(2\pi\theta)} \\
&= \mathrm{e}^{-\frac{x^2}{2\theta}+x-\frac{1}{2}\theta-\frac{1}{2}\ln(2\pi\theta)} \\
&= \mathrm{e}^{c(\theta)T(x)+d(\theta)+S(x)}
\end{aligned}
$$
em que
$$
\begin{array}{cc}
c(\theta) = -\frac{1}{2\theta}, & T(x) = x^2 \\
d(\theta) = -\frac{1}{2}\theta-\frac{1}{2}\ln(2\pi\theta), & S(x) = x.
\end{array}
$$
Portanto, $f_\theta$ pertence à FE.

#### Exemplo 6 - Exemplo negativo (Uniforme)
Se $X\sim U(0,\theta), \theta \in (0,\infty)$, então a sua função densidade de probabilidade não pertence à FE, pois
o seu suporte depende de "$\theta$".
$$
f_\theta(x) = \left\{\begin{array}{lr}
\frac{1}{\theta}, & x \in (0, \theta) \\
0, & x \not \in (0, \theta)
\end{array}\right.
$$

Dessa forma, $\mathfrak{X} = \{ x : f_\theta(x)> 0\} = (0,\theta)$.

#### Exemplo 7 - Exemplo negativo (Normal - Média e Variância)
Considere que $X \sim N(\mu,\sigma^2)$, em que $\theta = (\mu, \sigma^2) \in \mathbb{R}\times\mathbb{R}^+$. Então,
pode-se mostrar que a sua função densidade de probabilidade não pertence à FE **unidimensional**.

Observe que
$$
\begin{aligned}
f_\theta(x) &= \frac{1}{\sqrt{2\pi\sigma^2}} \mathrm{e}^{-\frac{1}{2\sigma^2}(x-\mu)^2} \\
&= \mathrm{e}^{-\frac{1}{2\sigma^2}(x^2-2x\mu+\mu^2) - \frac{1}{2} \ln (2\pi\sigma^2)} \\
&= \mathrm{e}^{-\frac{1}{2\sigma^2}x^2+\frac{x\mu}{\sigma^2}-\frac{1}{2\sigma^2}\mu^2-\frac{1}{2}\ln(2\pi\sigma^2)}
\end{aligned}
$$

portanto, não é possível definir $c(\theta),T(x),d(\theta)$ e $S(x)$ tais que $c(\cdot), T(\cdot)$ representem
$-\frac{1}{2\sigma^2}x^2 + \frac{x\mu}{\sigma^2}$.

### Propriedades na integração
Como $f_\theta$ é uma função (densidade) de probabilidade, temos que
$$
\int_{-\infty}^{\infty} f_\theta(x) dx = 1 \mathrm{(caso \ contínuo)}, \forall \theta \in \Theta
$$

Se $f_\theta$ pertence à FE unidimensional, então

$$
\begin{aligned}
&\int_{\mathfrak{X}} \mathrm{e}^{c(\theta)T(x) +d(\theta) + S(x)} dx = 1 \forall \theta \in \Theta \\
\Rightarrow& \int_{\mathfrak{X}} \mathrm{e}^{c(\theta)T(x) + S(x)} dx = \mathrm{e}^{-d(\theta)} \forall \theta \in \Theta.
\end{aligned}
$$

## Família Exponencial k-dimensional {#sec-fek}

Dizemos que a função (densidade) de probabilidade $f_\theta$ pertence à FE k-dimensional se, e somente se,
$$
f_\theta(x) = \left\{\begin{array}{lr}
\mathrm{e}^{\sum^k_{j=1} c_j(\theta)T_j(x)+d(\theta)+S(x)}, &x \in \mathfrak{X} \\
0, & x \not \in \mathfrak{X}
\end{array}\right.
$$
em que

1. $\mathfrak{X} = \{ x: f_\theta (x) > 0 \}$ não depende de "$\theta$";

2. As funções $c_1(\cdot),\dots,c_k(\cdot)$ e $d(\cdot)$ dependem apenas de "$\theta$" (formas conhecidas) e

3. As funções $T_1(\cdot),\dots,T_l(\cdot)$ e $S(\cdot)$ dependem apenas de $x$ (formas conhecidas).

Como $f_\theta$ é uma função (densidade) de probabilidade, temos que (para o caso contínuo)
$$
\int_{-\infty}^{\infty} f_\theta(x)dx=1 \forall \theta \in \Theta.
$$

Se $f_\theta$ pertence à FE k-dimensional, então
$$
\begin{aligned}
&\int_{\mathfrak{X}} \mathrm{e}^{\sum^k_{j=1}c_j(\theta)T_j(x) +d(\theta) + S(x)} dx = 1 \forall \theta \in \Theta \\
\Rightarrow &\int_{\mathfrak{X}} \mathrm{e}^{\sum^k_{j=1}c_j(\theta)T_j(x) + S(x)} dx = \mathrm{e}^{-d(\theta)} \forall \theta \in \Theta.
\end{aligned}
$$

### Exemplos

#### Exemplo 1 (Normal - Média e Variância)
Seja $X\sim N(\mu, \sigma^2)$, em que $\theta = (\mu, \sigma^2) \in \mathbb{R}\times\mathbb{R}^+$. Mostre que a sua
função densidade de probabilidade pertence à FE de dimensão 2.

##### Resposta
Note que
$$
\begin{aligned}
f_\theta(x) &= \mathrm{e}^{-\frac{1}{2\sigma^2}x^2+\frac{x\mu}{\sigma^2}-\frac{1}{2\sigma^2}\mu^2-\frac{1}{2}\ln(2\pi\sigma^2)}
&= \mathrm{e}^{c_1(\theta)T_1(x) + c_2(\theta)T_2(x) + d(\theta) + S(x)}
\end{aligned}
$$

em que
$$
\begin{array}{cc}
c_1(\theta) = -\frac{1}{2\sigma^2}, & T_1(x) = x^2 \\
c_2(\theta) = \frac{\mu}{\sigma^2}, & T_2(x) = x \\
d(\theta) = -\frac{1}{2}\frac{\mu^2}{\sigma^2}-\frac{1}{2}\ln(2\pi\sigma^2), & S(x) = 0
\end{array}
$$

### Exercício

Refaça o exemplo 5 do caso univarido com $N(\theta, \theta^2)$ e mostre que pertence à FE de dimensão 2.
