# População e Amostra

Veja: [Modelo Estatístico](modelo-estatistico.qmd) para definições dos modelos estatísticos paramétricos.

## Variável Populacional {#sec-vp}

Pela teoria estatística, população é o conjunto sob investigação de todos os potenciais elementos.

A *Variável Populacional* representa os valores numéricos de cada elemento da população:
$$
X\sim f_{\theta,}\theta \in \Theta
$$
em que $f_\theta$ é a Função Densidade de Probabilidade da Variável Aleatória populacional. $\theta$ é o vetor de
parâmetros (desconhecido) e $\Theta$ é o espaço paramétrico

## Amostra (Teórica)

Na estatística descritiva, a amostra é definida como um subconjunto da população.

Alguns livros utilizam o termo "amostra representativa" para representar a amostra
confiável de outra amostra que carrega determinados viéses de seleção. O termo
representativo é controverso na estatística teórica,

### Amostra Aleatória {#sec-aa}

Na estatística teórica, dizemos que $(X_{1},\dots,X_{n})$ é uma amostra aleatória
de $X$ (v.a. populacional) se $X_{1},\dots,X_{n}$ forem 
independentes e identicamente distribuídas de acordo com a distribuição da variável aleatória populacional $X$
Ou seja, 
$$
\text{Independentes }\rightarrow\begin{cases}X_{1}\sim f_{\theta,}\theta \in \Theta \\
. \\
. \\
. \\
X_{n} \sim f_{\theta}, \theta \in \Theta
\end{cases}
$$

Sendo assim, $(X_1, \dots, X_n)$ é amostra aleatória de $X\sim f_\theta, \theta in \Theta$
sempre que $(X_1, \dots, X_n)$ forem independentes para cada $P_\theta, \theta \in \Theta$ e
$X_i \sim f_\theta, \theta \in \Theta, i = 1, 2, \dots, n$

## Amostra (Observada) {#sec-ao}

É formada por valores numéricos após utilizar um procedimento de amostragem.
$$
x_{1},\dots,x_{n}
$$

em que $n$ é o tamanho amostral.

## Diagrama

```{.tikz width=100%}
%%| format: tex
%%| filename: diagramaamostra
%%| fig-cap: Diagrama: População, amostra aleatória e observada
\begin{tikzpicture}[node distance=0.8cm and 0.5cm, thick]

  \node (X1) [draw,  minimum width=2cm, minimum height=1cm] {$X_1
  \sim f_\theta, \ \theta \in \Theta$};

  \node (X2) [right=of X1, draw,  minimum width=2cm, minimum
  height=1cm] {$X_2 \sim f_\theta, \ \theta \in \Theta$};

  %\node (Xn) [right=of X2, draw, ellipse, minimum width=2cm, minimum
  % height=1cm] {$X_n \sim f_\theta, \ \theta \in \Theta$};

  \node (dots) [right=of X2] {...};

  \node (XnPlus) [right=of dots, draw,  minimum width=2cm, minimum
  height=1cm] {$X_{n} \sim f_\theta, \ \theta \in \Theta$};

  % Top Node

  \node (Y) [above=of X2, xshift=0.5cm, draw,  minimum width=2.5cm,
  minimum height=1cm] {$X \sim f_\theta, \ \theta \in \Theta$, $g(\theta)$};

  % Arrows

  \draw[-Latex] (Y) -- (X1);

  \draw[-Latex] (Y) -- (X2);

  \draw[-Latex] (Y) -- (XnPlus);

  % Bottom Nodes

  \node (x1) [below=of X1, draw,  minimum size=1cm] {$x_1$};

  \node (x2) [below=of X2, draw,  minimum size=1cm] {$x_2$};

  \node (dotss) [below=1.5cm of dots] {...};

  \node (xn) [below=of XnPlus, draw,  minimum size=1cm] {$x_n$};

  % Lines

  \draw[-Latex] (X1) -- (x1);

  \draw[-Latex] (X2) -- (x2);

  \draw[-Latex] (XnPlus) -- (xn);

  % Labels

  %\node[align=center] at (current bounding box.north) {\textbf{Diagrama}};

  \node[align=center, right=of xn] {\textbf{Amostra
  observada}};\node[align=center, right=of Y] {\textbf{Vetor
  aleatório populacional}};

  \node[align=center, right=of XnPlus] {\textbf{Amostra aleatória}};

  % Theory and Practice Box

  %\node[draw, align=left, right=of Y, minimum width=3cm, minimum
  % height=4cm, label=above:Teoria] (theory) {Gráficos,\\ medidas-resumo};

  %\node[draw, align=left, below=of theory, minimum width=3cm,
  % minimum height=4cm, label=above:Prática] (practice) {};

\end{tikzpicture}
```
